### ISSUE TITLE
installation guide requires an update

### ISSUE THREAD

**Issue by simonjenga** [AdamBien/lightfish#25]
I checked out the project and when i was trying to build it from the multi-light folder, it fails. This is because some modules require JDK 1.7 while other modules require JDK 1.8. However this has not been mentioned in the ```Installation:``` guide/ which only mentions steps 1) , 2) and 3)

```./multilight>mvn clean install```
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile)
on project lightview: Compilation failure
[ERROR] Failure executing javac, but could not parse the error:
[ERROR] javac: invalid target release: 1.8
```

**Comment by AdamBien** [comment]
Installation description fixed
