### ISSUE TITLE
Error when active the lighfish

### ISSUE THREAD

**Issue by zigic88** [AdamBien/lightfish#26]
First  of all, sorry for my bad english.
I'm already deploy lightfish on my glassfish 4.0.
When i'm point my browser to: http://localhost:8080/lightfish
and I press the active button. 
I got this error message :  
javax.ws.rs.RedirectionException: HTTP 302 Found
I'm using centos on my server.

Help me, please...

**Comment by AdamBien** [comment]
Tested with Payara (is GlassFish v4.1). It seems to work. Activate monitoring first? (click on the monitoring button before starting the collection)
